version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["/app/entrypoint.sh"]
    env_file:
      - ./.env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./team:/app/backend/static/uploads/team
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    env_file:
      - ./.env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    ports:
      - "8080:80"     # Changed from 80 to 8080
      - "8443:443"    # Changed from 443 to 8443
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: {}