"""check_model_sync

Revision ID: 76bac7b851b5
Revises: manual01
Create Date: 2025-05-21 22:29:31.689129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bac7b851b5'
down_revision: Union[str, None] = 'manual01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('title',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('description',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        batch_op.create_index(op.f('ix_properties_title'), ['title'], unique=False)
        batch_op.create_foreign_key('fk_properties_assigned_to_id_users', 'users', ['assigned_to_id'], ['id'])
        batch_op.create_foreign_key('fk_properties_owner_id_users', 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key('fk_properties_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])
        batch_op.drop_column('area')

    with op.batch_alter_table('property_clicks', schema=None) as batch_op:
        batch_op.alter_column('clicked_at',
                   existing_type=sa.DATETIME(),
                   nullable=True,
                   existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(op.f('ix_property_clicks_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_property_clicks_property_id_properties', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_clicks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_property_clicks_property_id_properties', type_='foreignkey')
        batch_op.drop_index(op.f('ix_property_clicks_id'))
        batch_op.alter_column('clicked_at',
                   existing_type=sa.DATETIME(),
                   nullable=False,
                   existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('fk_properties_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_properties_owner_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_properties_assigned_to_id_users', type_='foreignkey')
        batch_op.drop_index(op.f('ix_properties_title'))
        batch_op.alter_column('description',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        batch_op.alter_column('title',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    # ### end Alembic commands ###
